apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: search
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "es-data"