apiVersion: v1
kind: Pod
metadata:
  name: es
  namespace: search
  labels:
    app: es
spec:
  containers:
  - name: es
    image: elasticsearch:8.0.0
    volumeMounts:
      - name: es-data
        mountPath: /usr/share/elasticsearch/data
    env:
      - name: "ES_JAVA_OPTS"
        value: "-Xms2G -Xmx2G"
      - name: "cluster.name"
        value: "es"
      - name: "xpack.security.enabled"
        value: "false"
      - name: "xpack.ml.enabled"
        value: "false"
      - name: "ingest.geoip.downloader.enabled"
        value: "false"
      - name: "cluster.initial_master_nodes"
        value: "es"
      - name: "http.cors.enabled"
        value: "true"
      - name: "http.cors.allow-origin"
        value : "*"
    readinessProbe:
      httpGet:
        path: /_cluster/health?local=true
        port: 9200
      initialDelaySeconds: 20
      periodSeconds: 10
    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 4Gi    
  volumes:
    - name: es-data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: search
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 30100
  selector:
    app: es


