apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data
  namespace: search
spec:
  storageClassName: es-data
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/es-volume/